x-templates:
  volumes: &volumes
    volumes:
      - "caches:/root/caches-named-volume"
      - "./data/caches:/root/caches-bind-mount"
      - "playgrounds:/root/playgrounds-named-volume"
      - "./data/playgrounds:/root/playgrounds-bind-mount"
      - "./data/playbooks:/root/playbooks"
  hook-base:
    <<: *volumes
    user: hook

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      - ./assets/redis:/usr/local/etc/redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - bridge
  conflict-playground:
    build: 
      context: .
      dockerfile: Dockerfile
    image: conflict-playground:playground
    container_name: conflict-playground
    environment:
      LOGURU_LEVEL: INFO
    networks:
      - bridge
    <<: *volumes
  hook-manual-cli:
    build: 
      context: .
      dockerfile: src-hooks/manual-cli/Dockerfile
    image: conflict-playground-hook:manual-cli
    container_name: conflict-playground-hook-manual-cli
    networks:
      - bridge
    <<: *volumes
  hook-opencode:
    build: 
      context: .
      dockerfile: src-hooks/opencode/Dockerfile
    image: conflict-playground-hook:opencode
    container_name: conflict-playground-hook-opencode
    networks:
      - bridge
    <<: *volumes
volumes:
  caches:
  playgrounds:
  redis:
networks:
  bridge:
    name: conflict-playground-bridge
    driver: bridge